// <auto-generated />
using System;
using DaLatBooking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaLatBooking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240213101200_addVillaNumber")]
    partial class addVillaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaLatBooking.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Phòng gỗ của chúng tôi là một kỳ quan đích thực của sự sáng tạo và tự nhiên. Tấm ván gỗ tự nhiên được sử dụng cho cả tường và sàn, tạo ra một không gian ấm áp và mộc mạc. Chiếc giường gỗ chắc chắn được bố trí giữa phòng với ga trải giường mềm mại, tạo điều kiện lý tưởng cho một giấc ngủ ngon lành",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Phòng Gỗ",
                            Occupancy = 4,
                            Price = 800.0,
                            Sqft = 500
                        },
                        new
                        {
                            Id = 2,
                            Description = "Phòng đá của chúng tôi là một biểu tượng của sức mạnh và sự vững chãi của thiên nhiên. Tường và sàn được lát bằng các tấm đá tự nhiên, tạo ra một không gian mát mẻ và bền vững. Không gian rộng rãi và thoải mái với đồ nội thất đơn giản nhưng đầy tính thẩm mỹ",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Phòng Đá",
                            Occupancy = 4,
                            Price = 1200.0,
                            Sqft = 600
                        },
                        new
                        {
                            Id = 3,
                            Description = "Phòng homestay bình thường của chúng tôi được thiết kế để mang lại sự tiện nghi và thoải mái cho du khách. Với không gian rộng rãi và ánh sáng tự nhiên, phòng homestay mang lại cảm giác ấm cúng và thân thiện",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Phòng Thường",
                            Occupancy = 2,
                            Price = 400.0,
                            Sqft = 300
                        });
                });

            modelBuilder.Entity("DaLatBooking.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 104,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 303,
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("DaLatBooking.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("DaLatBooking.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
